### ISSUE TITLE
Add DeleteIfExist to prior creating a container make sure it is deleted.

### ISSUE THREAD

**Issue by DrLeh** [mariotoffia/FluentDocker#205]
I'm working on putting in FluentDocker into some unit tests for elasticsearch. Under some circumstances, the container sometimes isn't getting disposed. Like if I'm debugging through the test and stop debugging, sometimes it seems Dispose() is not getting called.

I see we have the `ReuseIfExists()` method, which is nice, but is there any way to do `DeleteIfExists()` / `ReCreateIfExists()`? For a unit test I always want the container to be fresh, so I don't want `.Build()` or `Start()` to fail.

I could presumably do something like this but it feels really janky:

```
var b = new Builder().UseContainer()
    .ResuseIfExists() //so it doesn't error if exists
   //...
    ;

var container = b.Build();
container.Dispose();
container = b.Build();
container.Start();

```

**Comment by mariotoffia** [comment]
That's true, if you have it in a `using` statement, you have to let it run or throw an exception otherwise it will not call `Dispose`.

That is a really good idea!!

Hmm... I would vote for `DeleteIfExist`. I'll do that tonight/tomorrow.  I'll add this as an enhancement.

But it has to be on named containers only!

Cheers, 
 Mario :)

**Comment by mariotoffia** [comment]
Hi @DrLeh , I've implemented the `DeleteIfExists`. You probably need to wait one hour or so in order to tests and it to get published onto nuget.

Cheers,
 Mario :)

🐅 Sample usage

```cs
      var name = Guid.NewGuid().ToString();

      var container = Fd.UseContainer()
        .UseImage("postgres:9.6-alpine")
        .WithName($"name-{name}")
        .Build();

      var id = container.Id;

      using (var c = Fd
        .UseContainer()
        .DeleteIfExists() // <-- It will delete the named container if it exists *before* it creates the new one.
        .UseImage("postgres:9.6-alpine")
        .WithName($"name-{name}")
        .Build())
      {
        // Ids should not be equal - since deleted and then created.
        AreNotEqual(id, c.Id);
      }
```

**Comment by DrLeh** [comment]
@mariotoffia looks like i'm still getting an error when the container is still running:

![image](https://user-images.githubusercontent.com/1790357/133281545-f2584d83-de0a-4452-8b91-28acc4e1212d.png)


My code has IDisposable but it seems when i stop debugging it doesn't get called:
```C#    
public class ElasticContainerFixture : IDisposable
{
    public string ClusterName = "es-docker-cluster-elastic-ci-tests";

    public IContainerService Container;

    public void Dispose()
    {
        Container.Dispose();
    }

    public ElasticContainerFixture()
    {
        var b = new Builder().UseContainer()
             .UseImage("elasticsearch:7.14.1")
             .WithEnvironment(@"node.name=elastic-ci-tests",
                 @$"cluster.name={ClusterName}",
                 @"discovery.type=single-node",
                 @"""ES_JAVA_OPTS=-Xms512m -Xmx512m""")
             .ExposePort(9800, 9200)
             .ExposePort(9900, 9300)
             .WithName($"elastic-ci-tests_{Environment.MachineName.Replace(" ", "_")}")
             .DeleteIfExists()
             .WaitForHttp("http://localhost:9800", continuation: (req, i) =>
             {
                 //this is ultimately the same code they have in WaitForHttp with
                 //no continuation: specified. We might want to check a different url
                 if (req.Code == System.Net.HttpStatusCode.OK)
                     return 0L;
                 return 2000;
             });
        Container = b.Build();
        Container.Start();
    }
}
```

**Comment by mariotoffia** [comment]
Hi @DrLeh try to use option force: true when doing DeleteIfExists if that Will solve your problem. 

Yes, when you break it Will not call dispose - if you just continue - it will call it :)

but curious if force: true will solve the problem - could you please respond if it worked or not - if not I’ll fix it nos that I’ve got a unit test.

**Comment by DrLeh** [comment]
Thanks I didn't see that force option! Thanks for the incredibly quick turnaround, loving this library!
